name: expense_splitter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  pdfx: ^2.6.0
  fl_chart: ^0.66.0
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.0
  lottie: ^3.1.0
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  animations: ^2.0.11
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
    
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf

  assets:
    - assets/backgrounds/food.jpg
    - assets/backgrounds/transport.jpg
    - assets/backgrounds/shopping.jpg
    - assets/backgrounds/Accomo.jpg
    - assets/backgrounds/trip.jpg
    - assets/backgrounds/others.jpg
    - assets/images/crumpled_ball.png
    - assets/images/receipt.jpg
    - assets/lottie/
    - assets/icons/
    - assets/rabbits/Running rabbit.json
    - assets/rabbits/bunny_hop.json
    - assets/rabbits/Rabbit Kick Scooter.json
    # ✅ Fixed the spacing here:
    - assets/videos/food.MP4
    - assets/videos/transport.MP4
    - assets/videos/shopping.MOV
    - assets/videos/Accomo.MP4
    - assets/videos/trip.MP4
    - assets/videos/others.MP4
    - assets/sounds/Acco_sound.mp3
    - assets/sounds/food_sound.mp3
    - assets/sounds/shopping_sound.mp3
    - assets/sounds/transport_sound.mp3
    - assets/sounds/trip_sound.mp3
    - assets/sounds/other_sound.mp3